application:
  id: jpa-tutorial
  version: 1.0

server:
  port: 8888

server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:33333/jpa-study?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # query가 formatted 되어서 출력 된다.
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true # System.out 으로 쿼리를 출력 한다.
    database: mysql

logging:
  level:
    org.hibernate.SQL: debug # hibernate ???? ?? ??? debug ? ?? ?.
    org.hibernate.type: trace # parameter log printing ???.
