spring:
  datasource:
    url: jdbc:mysql://localhost:33333/jpa-study?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # hibernate ???? ?? ??? debug ? ?? ?.
    org.hibernate.type: trace # parameter log printing ???.